backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "_data/contact.json"
        label: "Contact Information"
        name: "contact"
        fields:
          - {label: "Primary Email", name: "email_primary", widget: "string", default: "sales.giftority@gmail.com"}
          - {label: "Support Email", name: "email_support", widget: "string", default: "support.giftority@gmail.com"}
          - {label: "Primary Phone", name: "phone_primary", widget: "string", default: "+91 XXXXX XXXXX"}
          - {label: "Secondary Phone", name: "phone_secondary", widget: "string", default: "+91 XXXXX XXXXX"}
          - {label: "Business Hours", name: "hours", widget: "string", default: "Mon-Sat: 9:00 AM - 7:00 PM IST"}
          - {label: "Address Line 1", name: "address_line1", widget: "string"}
          - {label: "Address Line 2", name: "address_line2", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
          - {label: "State", name: "state", widget: "string"}
          - {label: "PIN Code", name: "pin", widget: "string"}
          - {label: "Instagram URL", name: "social_instagram", widget: "string"}
          - {label: "Facebook URL", name: "social_facebook", widget: "string"}
          - {label: "LinkedIn URL", name: "social_linkedin", widget: "string"}
          - {label: "Twitter URL", name: "social_twitter", widget: "string"}

  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Corporate","Wedding","Personal","Christmas"]}
      - {label: "Sub-Category", name: "subcategory", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Product Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Features", name: "features", widget: "list", field: {label: "Feature", name: "feature", widget: "string"}}
      - {label: "Featured?", name: "featured", widget: "boolean", default: false}
      - {label: "Available", name: "available", widget: "boolean", default: true}
      - {label: "Bulk Pricing", name: "bulk_pricing", widget: "boolean", default: false}
      - {label: "Customizable", name: "customizable", widget: "boolean", default: false}

  - name: "experiences"
    label: "Experiences"
    folder: "experiences"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Experience Name", name: "name", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Corporate Team Building","Spa & Wellness","Fine Dining","Adventure","Workshops","Entertainment"]}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "What's Included", name: "whats_included", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
      - {label: "Available", name: "available", widget: "boolean", default: true}

  - name: "packages"
    label: "Event Packages"
    folder: "packages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Package Name", name: "name", widget: "string"}
      - {label: "Package Type", name: "type", widget: "select", options: ["Wedding","Corporate Event","Birthday","Anniversary","Festival","Christmas"]}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "What's Included", name: "included", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
      - {label: "Package Image", name: "image", widget: "image", required: false}
      - {label: "Guest Count", name: "guest_count", widget: "string", hint: "e.g., 50-100 guests"}
      - {label: "Available", name: "available", widget: "boolean", default: true}

  - name: "testimonials"
    label: "Testimonials"
    folder: "testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Customer Name", name: "name", widget: "string"}
      - {label: "Company/Occasion", name: "company", widget: "string", required: false}
      - {label: "Testimonial Text", name: "text", widget: "text"}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, default: 5}
      - {label: "Service Used", name: "service", widget: "select", options: ["Corporate Gifting","Wedding & Events","Personal Gifting","Christmas Services"]}
      - {label: "Show on Homepage", name: "homepage", widget: "boolean", default: false}

  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "_data/homepage.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string", default: "Gift Beyond Things. Gift Memories."}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
          - {label: "Hero Background Image", name: "hero_image", widget: "image", required: false}
          - {label: "Christmas Banner Text", name: "christmas_text", widget: "string"}
          - {label: "Show Christmas Banner", name: "show_christmas", widget: "boolean", default: true}

publish_mode: editorial_workflow
